# Dockerfile.frontend

# 1. Image de base
FROM python:3.12-slim

# 2. Répertoire de travail
WORKDIR /app

# 3. Copier les fichiers requirements.txt
COPY requirements.txt .

# 4. Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# 5. Copier tout le code du frontend
COPY . .

# 6. Exposer le port Streamlit
EXPOSE 8501

