FROM python:3.12-slim

WORKDIR /app

# Copier le code et le requirements
COPY . /app
COPY requirements.txt /app/requirements.txt

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Commande par défaut
CMD ["python", "main.py"]
